version: "3.3"
name: "screener-backend"
services:
  ## Storage containers for the backend
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: app
    ports:
      - "54320:5432"

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
volumes:
  postgres-data: {}
  redis-data: {}
